### PR TITLE
Change branch to `develop` in contrib workflow

### PR DESCRIPTION
**Pull request by descent3me**
**What this PR does / why we need it**:
Updates workflow with our branching model.

**Which issue(s) this PR fixes** 

Fixes # N/A

**Special notes for your reviewer**:
N/A

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by descent3me** [comment]
@econchick

**Comment by descent3me** [comment]
@spotify/alf ping (the checks have failed because there aren't any tests in this repo yet)

**Comment by descent3me** [comment]
Also, I realize it's ironic that I'm making this change into master, but it isn't part of any development chunk and I think it'd be helpful to get the docs updated as soon as possible.

**Comment by smstone** [comment]
+1

**Pull request merged**
