### PR TITLE
fix some typos and inconsistencies in formatting

### PR DESCRIPTION
**Pull request by ocsw**
**What this PR does / why we need it**:
Fixes some typos and inconsistencies in formatting, also removes a NOQA that doesn't seem to be necessary anymore.

**Which issue(s) this PR fixes** 

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by descent3me** [comment]
Everything looks ok, but are the things like capitalization/periods covered in any of the docs/style guide? I tend not to care about them for args lists since those aren't really sentences, so I would actually be more inclined to remove periods there (in the cases where they exist), rather than capitalize, but of course I'll go with whatever standard we chose as long as we're explicit about choosing it.

**Comment by ocsw** [comment]
The caps/periods aren't 100% explicitly listed, but that's how they do it
in the examples, and how we do it elsewhere.

**Comment by ocsw** [comment]
https://google.github.io/styleguide/pyguide.html#Comments

**Comment by descent3me** [comment]
+1

**Pull request merged**
